SELECT COURSE_NAME, GRADE, S.S_ID
FROM ENROLLMENT E
JOIN STUDENT S
    ON E.S_ID = S.S_ID
JOIN COURSE_SECTION CS
    ON E.C_SEC_ID = CS.C_SEC_ID
JOIN COURSE C
    ON CS.COURSE_ID = C.COURSE_ID
WHERE S_FIRST = 'Tammy'
AND S_LAST = 'Jones'