SELECT DISTINCT S_LAST, S_FIRST
FROM STUDENT S
JOIN ENROLLMENT E
    ON S.S_ID = E.S_ID
WHERE E.C_SEC_ID IN (
SELECT E.C_SEC_ID
FROM STUDENT S
JOIN ENROLLMENT E
    ON S.S_ID = E.S_ID
WHERE S_FIRST = 'Jorge'
AND S_LAST = 'Perez'
)