CREATE TEMPORARY TABLE
    tmpUPDATE (C_SEC_ID INT);
INSERT INTO tmpUPDATE
SELECT C_SEC_ID FROM COURSE_SECTION CS
JOIN FACULTY F
    ON CS.F_ID = F.F_ID
WHERE F.F_LAST = 'BROWN';
UPDATE COURSE_SECTION 
SET LOC_ID = 8
WHERE C_SEC_ID IN (
SELECT C_SEC_ID FROM tmpUPDATE);

SELECT * FROM COURSE_SECTION;
