CREATE TABLE ENROLLMENT_NUMBERS (
COURSE_ID INTEGER,
C_SEC_ID INTEGER,
ENROLLMENTS INTEGER);

INSERT INTO ENROLLMENT_NUMBERS
SELECT COURSE_ID, CS.C_SEC_ID, COUNT(S_ID) AS ENROLLMENTS
FROM COURSE_SECTION CS
JOIN ENROLLMENT E
    ON CS.C_SEC_ID = E.C_SEC_ID
JOIN TERM T
    ON CS.TERM_ID = T.TERM_ID
WHERE T.TERM_DESC = 'SPRING 2008'
GROUP BY COURSE_ID, CS.C_SEC_ID;

SELECT * FROM ENROLLMENT_NUMBERS;